# Generated by Django 2.2.4 on 2021-02-06 03:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertymessage',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller_details', to='users.Seller'),
        ),
        migrations.AddField(
            model_name='property',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller', to='users.Seller'),
        ),
        migrations.AddField(
            model_name='customerfavoriteproperty',
            name='buyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyer', to='users.Buyer'),
        ),
        migrations.AddField(
            model_name='customerfavoriteproperty',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property', to='properties.Property'),
        ),
        migrations.AlterUniqueTogether(
            name='customerfavoriteproperty',
            unique_together={('buyer', 'property')},
        ),
    ]
